### ISSUE TITLE
Archmain doesn't launch in arcolinux

### ISSUE THREAD

**Issue by pommedefrance** [JonathanSanfilippo/Archmain#25]
i'm ok in garuda linux but with arcolinux nothing
when i launch manually with python thepath/archmain.py i've got this...

Traceback (most recent call last):
  File "/mypath/archmain/archmain.py", line 175, in <module>
    switch_1 = customtkinter.CTkSwitch(master=app, text="Login Splash", command=switch_event,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mypath/.local/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_switch.py", line 57, in __init__
    self._fg_color = ThemeManager.theme["CTkSwitch"]["fg_color"] if fg_color is None else self._check_color_type(fg_color)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'fg_color'

any idea ?
thks

PS: after one month, i'm ok now, sorry..perhaps an arch update (i do it every day) ?
still i've got 2 others questions with syslog-ng and "those packages don't exist in AUR"...both arco and garuda..but i can open new ticket.. ;-)

**Comment by jonalinux** [comment]
i have fix this in new version

**Comment by pommedefrance** [comment]
that's why it works now ;-)
thks
i open other tickets for my others problems ?
